import type { Metadata } from 'next'
import { LegalShell, Section, P, UL, Strong, A } from '@/components/legal-shell'

export const metadata: Metadata = {
  title: 'terms of service — friday',
  description: 'The terms that govern your use of the Friday desktop app and website.'
}

export default function TermsPage() {
  return (
    <LegalShell title="terms of service" lastUpdated="June 30, 2026">
      <Section title="">
        <P>
          These Terms of Service (“Terms”) govern your access to and use of the Friday desktop
          application and the friday.feynmanpi.com website (together, the “Service”), operated by
          Sagar Tamang (feynmanpi). By downloading, installing, or using Friday, you agree to these
          Terms. If you do not agree, do not use the Service.
        </P>
      </Section>

      <Section title="1. What Friday is">
        <P>
          Friday is a voice-first AI assistant that runs on your computer. It can hold spoken
          conversations, look at your screen when asked, search the web, and — when you instruct it
          — control your computer by moving the mouse and typing. Friday works on a “bring your own
          key” basis: you supply your own OpenAI API key, and Friday uses it to access the underlying
          AI models.
        </P>
      </Section>

      <Section title="2. Eligibility">
        <P>
          You must be at least 13 years old (or the age of digital consent in your country) and able
          to form a binding contract to use the Service.
        </P>
      </Section>

      <Section title="3. Your API key and costs">
        <UL>
          <li>
            You are responsible for obtaining your own OpenAI API key and for keeping it secure.
          </li>
          <li>
            All usage of that key — including any fees, charges, or rate limits billed by OpenAI — is
            your responsibility. Friday does not control or reimburse those costs.
          </li>
          <li>
            You agree to comply with OpenAI’s and any other provider’s terms of use when using
            Friday.
          </li>
        </UL>
      </Section>

      <Section title="4. Acceptable use">
        <P>You agree not to use Friday to:</P>
        <UL>
          <li>break any law or regulation, or infringe anyone’s rights;</li>
          <li>
            access, modify, or damage systems, accounts, or data you are not authorized to use;
          </li>
          <li>generate or distribute malware, spam, or harmful content;</li>
          <li>harass, harm, deceive, or violate the privacy of others.</li>
        </UL>
        <P>
          You are solely responsible for the instructions you give Friday and the actions it takes
          on your behalf.
        </P>
      </Section>

      <Section title="5. Computer control — important">
        <P>
          Friday can control your computer (mouse and keyboard) when you ask it to. This is powerful
          and carries risk:
        </P>
        <UL>
          <li>
            <Strong>AI can make mistakes.</Strong> Friday may misunderstand an instruction or take an
            unintended action, including actions that are difficult or impossible to undo.
          </li>
          <li>
            You are responsible for <Strong>supervising Friday</Strong> whenever it controls your
            computer, and for any consequences of those actions.
          </li>
          <li>
            Do not leave Friday unattended while it operates your machine, and stop it if it begins
            doing something you did not intend.
          </li>
          <li>
            Do not use the computer-control feature for any unlawful, harmful, or unauthorized
            purpose.
          </li>
        </UL>
        <P>
          We strongly recommend not using computer control around sensitive accounts, financial
          transactions, or irreversible operations without close supervision.
        </P>
      </Section>

      <Section title="6. AI output and accuracy">
        <P>
          Friday’s responses are generated by AI and may be inaccurate, incomplete, or out of date.
          Friday is not a substitute for professional advice (legal, medical, financial, or
          otherwise). You are responsible for evaluating and verifying any information or action
          before relying on it.
        </P>
      </Section>

      <Section title="7. Third-party services">
        <P>
          Friday depends on third-party services, including OpenAI and Google. Your use of those
          services through Friday is also subject to their respective terms and policies. We are not
          responsible for third-party services, their availability, or their content.
        </P>
      </Section>

      <Section title="8. Software and intellectual property">
        <P>
          The Friday desktop application and the Service are proprietary and owned by Sagar Tamang
          (feynmanpi). We grant you a personal, non-exclusive, non-transferable, revocable license to
          download and use Friday for its intended purpose, subject to these Terms. You may not copy,
          modify, distribute, sell, rent, sublicense, reverse-engineer, or create derivative works
          from the Service except to the extent that applicable law expressly permits. All rights not
          expressly granted to you are reserved by us.
        </P>
        <P>
          A separate, open-source edition of Friday is published under the MIT License on GitHub.
          That license governs only that public source code — it does not apply to this Service, the
          desktop builds distributed here, or their additional features.
        </P>
      </Section>

      <Section title="9. Disclaimers">
        <P>
          THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE”, WITHOUT WARRANTIES OF ANY KIND, WHETHER
          EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY,
          FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. We do not warrant that the Service
          will be uninterrupted, error-free, or secure.
        </P>
      </Section>

      <Section title="10. Limitation of liability">
        <P>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, FRIDAY AND ITS OPERATOR WILL NOT BE LIABLE FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF DATA,
          PROFITS, OR GOODWILL, ARISING FROM OR RELATED TO YOUR USE OF THE SERVICE — including,
          without limitation, any actions Friday takes while controlling your computer, any API costs
          you incur, or any data loss.
        </P>
      </Section>

      <Section title="11. Indemnification">
        <P>
          You agree to indemnify and hold harmless Friday and its operator from any claims, damages,
          or expenses arising out of your use of the Service, your instructions to Friday, or your
          violation of these Terms.
        </P>
      </Section>

      <Section title="12. Termination">
        <P>
          You may stop using Friday at any time by uninstalling it. We may suspend or terminate
          access to the hosted Service if you violate these Terms or to protect the Service or its
          users.
        </P>
      </Section>

      <Section title="13. Changes to these terms">
        <P>
          We may update these Terms from time to time. We will revise the “Last updated” date above,
          and your continued use of the Service after changes take effect constitutes acceptance.
        </P>
      </Section>

      <Section title="14. Governing law">
        <P>
          These Terms are governed by the laws of India, without regard to its conflict-of-law
          principles.
        </P>
      </Section>

      <Section title="15. Contact">
        <P>
          Questions about these Terms? Email us at{' '}
          <A href="mailto:build@sagartamang.com">build@sagartamang.com</A>.
        </P>
      </Section>
    </LegalShell>
  )
}
